// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4oqih6cyeiU6OoUjNGwT05kpCLE7IAKo',
    appId: '1:747596867305:web:1d29db65caa5a2c2a3b278',
    messagingSenderId: '747596867305',
    projectId: 'autentificacion-780ff',
    authDomain: 'autentificacion-780ff.firebaseapp.com',
    storageBucket: 'autentificacion-780ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE2K_EqDFODsKof4uZgGBJwOpP5FWkFLU',
    appId: '1:747596867305:android:8d055f7976e7fb90a3b278',
    messagingSenderId: '747596867305',
    projectId: 'autentificacion-780ff',
    storageBucket: 'autentificacion-780ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOADvnW2Q4Y4ZM2P5M1TdIDhNS2MUapVM',
    appId: '1:747596867305:ios:7314dab2ece12bf3a3b278',
    messagingSenderId: '747596867305',
    projectId: 'autentificacion-780ff',
    storageBucket: 'autentificacion-780ff.firebasestorage.app',
    iosClientId: '747596867305-e2pfb4s3l4et0b7ha97bll5o6tfik0ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.miAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOADvnW2Q4Y4ZM2P5M1TdIDhNS2MUapVM',
    appId: '1:747596867305:ios:7314dab2ece12bf3a3b278',
    messagingSenderId: '747596867305',
    projectId: 'autentificacion-780ff',
    storageBucket: 'autentificacion-780ff.firebasestorage.app',
    iosClientId: '747596867305-e2pfb4s3l4et0b7ha97bll5o6tfik0ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.miAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4oqih6cyeiU6OoUjNGwT05kpCLE7IAKo',
    appId: '1:747596867305:web:8b85c1b3ca7879efa3b278',
    messagingSenderId: '747596867305',
    projectId: 'autentificacion-780ff',
    authDomain: 'autentificacion-780ff.firebaseapp.com',
    storageBucket: 'autentificacion-780ff.firebasestorage.app',
  );
}
